### ISSUE TITLE
Blank node labels / identifiers

### ISSUE THREAD

**Issue by hartig** [w3c/rdf-turtle#22]
As already discussed at https://github.com/w3c/rdf-concepts/issues/38 and at https://github.com/w3c/sparql-query/issues/66, the term "blank node label" should be replaced by "blank node identifier" 

@TallTed already has a concrete proposal at https://github.com/w3c/rdf-concepts/issues/38#issuecomment-1540302419

**Comment by afs** [comment]
In the suggestion: https://github.com/w3c/rdf-concepts/issues/38#issuecomment-1540302419

The previous sentence ends "... in a document." so that part of the change isn't necessary.

If included, it should be "document" not "file".

**Comment by TallTed** [comment]
Bringing the suggested change here, and revising per @afs comment —

> Repeated use of the same blank node identifier in the same Turtle document identifies the same RDF blank node.

... except, as discussed elsewhere, within quoted triples in that Turtle document, which introduce multiple graphs to Turtle.

**Comment by pfps** [comment]
@TallTed That is not my understanding of how quoted triples are envisioned to work in Turtle 1.2.

**Comment by gkellogg** [comment]
Whether or not blank node identifiers writhing quoted triples identify those in asserted triples hasn’t been decided, and is unrelated to named graphs.

**Comment by TallTed** [comment]
My understanding of the discussion thus far is that our intent is that in `<< :Subj _:Pred _:Obj >> _:Pred _:Obj`, the two `_:Pred` and the two `_:Obj` would be distinct blank nodes — i.e., there would be 4 blank nodes which each occur once there, not 2 blank nodes which each occur twice.

(Note that I did not say anything about *named* graphs in Turtle, only about *multiple* graphs. Though I now think that indeed was a mis-think, so that can be set aside.)

**Comment by gkellogg** [comment]
> My understanding of the discussion thus far is that our intent is that in `<< :Subj _:Pred _:Obj >> _:Pred _:Obj`, the two `_:Pred` and the two `_:Obj` would be distinct blank nodes — i.e., there would be 4 blank nodes which each occur once there, not 2 blank nodes which each occur twice.

This is unresolved, and I personally am opposed to this interpretation, as it is quite unintuitive, and goes against the general understanding of what it means to identify blank nodes. The argument for is that, _if copied verbatim_, a quoted triple containing a blank node identifier could be unrelated to any other identifiers, much as if it were a literal value, however, this can be accommodated by renaming blank nodes when quoting, and otherwise provides no mechanism to, in fact, denote a blank node in an asserted triple. In any case, the meaning here is consistent with that in N-Triples and N-Quads, and any change in this interpretation would need to be handled comprehensively.
